version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elasticsearch
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=gramofon
      - cluster.initial_master_nodes=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - network.host=elasticsearch,_local_
      - network.publish_host=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms2G -Xmx2G
    ulimits: { nofile: { soft: 65535, hard: 65535 }, memlock: -1 }
    healthcheck:
      test: curl --head --max-time 120 --retry 120 --retry-delay 1 --show-error --silent http://localhost:9200

  jupyterlab:
    image: jupyter/base-notebook
    volumes:
      - $PWD/content:/home/jovyan/work
    networks:
      - elasticsearch
    ports:
      - 8888:8888

networks:
  elasticsearch:

volumes:
  data-elasticsearch:
